### PR TITLE
Patched to newest version of groovy and Jenkins.  Fixed NPE in promot…

### PR DESCRIPTION
**Pull request by efenglu**
Updated to latest Jenkins/Groovy and found an NPE. Patched.

### CODE REVIEW

**Comment by denschu** [comment]
Thanks! :-)

**Comment by denschu** [comment]
Hi @efenglu,
did you tested this successfully? I encountered some problems with the Job DSL Plugin, because it uses Groovy 1.x...

Thanks
Dennis

**Comment by efenglu** [comment]
I was able to run it successfully with the mvn hpi:run command.  I didn't
do extensive tests but was able to do a simple job dsl with promotion.

If it caused issues just roll it back.

I had issues getting it to build without increasing the version.  I'll try
again.  Sorry for the trouble.

On a side note what's the best way to install this normally.  Is it
considered a standard Jenkins plugin?

**Comment by denschu** [comment]
Ok, thanks for the fast replay. Now it works for me... I had some troubles with my local setup ;-)

Actually I'm in discussion withe the owners of the DSL Plugin. It seems that it's not fully clear where to put those DSL extensions. See here: https://issues.jenkins-ci.org/browse/JENKINS-21750

**Comment by efenglu** [comment]
Until this ticket is complete what should I do?  The plugin seems to do
what I want I just don't know how to add it to our production systems.

**Comment by denschu** [comment]
You can simply install the hpi-File as Plugin in Jenkins...
See: https://github.com/codecentric/job-dsl-promotions-plugin/releases/tag/1.0.RC1

**Comment by efenglu** [comment]
Awesome, I knew I was missing something simple.

**Comment by efenglu** [comment]
Do you know how I would add a PasswordParam in the dsl?  I figured out how
to add the string Param, but doesn't seem to support Password param or
other custom parameters.

**Comment by efenglu** [comment]
So I think I got it, but doesn't seem like the most 'groovy' way to do it.
Suggestions?

conditions {
                            manual('SUBMIT') {
                                stringParam('Username',  '', '')
                            }
                            Node node = new Node(null,
'hudson.model.PasswordParameterDefinition')
                            node.append(new Node(null, 'name', 'Password'))
                            node.append(new Node(null, 'defaultValue',
'1234567890'))
                            node.append(new Node(null, 'desciption', ''))
                            params +=  node
               }

**Pull request merged**
